/* Form definition file generated by fdesign on Sat Apr  1 15:44:10 2023 */

#include <stdlib.h>
#include "calc_top.h"



/***************************************
 ***************************************/

FD_calc_top *
create_form_calc_top( void )
{
    FL_OBJECT *obj;
    FD_calc_top *fdui = ( FD_calc_top * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->calc_top = fl_bgn_form( FL_NO_BOX, 600, 450 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 600, 450, "" );
    fl_set_object_color( obj, FL_CORNFLOWERBLUE, FL_COL1 );

    fdui->reg_Y = obj = fl_add_text( FL_NORMAL_TEXT, 90, 50, 480, 20, "text" );
    fl_set_object_color( obj, FL_BOTTOM_BCOL, FL_MCOL );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );

    obj = fl_add_box( FL_UP_BOX, 190, 110, 80, 20, "" );
    fl_set_object_color( obj, FL_WHITE, FL_COL1 );

    obj = fl_add_box( FL_UP_BOX, 90, 90, 170, 20, "" );
    fl_set_object_color( obj, FL_WHITE, FL_COL1 );

    fdui->d1 = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 340, 40, 30, "1" );
    fl_set_button_shortcut( obj, "1", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 1 );

    fdui->d2 = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 340, 40, 30, "2" );
    fl_set_button_shortcut( obj, "2", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 2 );

    fdui->d3 = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 340, 40, 30, "3" );
    fl_set_button_shortcut( obj, "3", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 3 );

    fdui->sub = obj = fl_add_button( FL_NORMAL_BUTTON, 90, 280, 40, 30, "-" );
    fl_set_button_shortcut( obj, "-", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 1 );

    fdui->add = obj = fl_add_button( FL_NORMAL_BUTTON, 90, 310, 40, 30, "+" );
    fl_set_button_shortcut( obj, "+", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 2 );

    fdui->mul = obj = fl_add_button( FL_NORMAL_BUTTON, 90, 340, 40, 30, "X" );
    fl_set_button_shortcut( obj, "*", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 3 );

    fdui->div = obj = fl_add_button( FL_NORMAL_BUTTON, 90, 370, 40, 30, "/" );
    fl_set_button_shortcut( obj, "/", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 4 );

    fdui->d_0 = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 370, 40, 30, "0" );
    fl_set_button_shortcut( obj, "0", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 0 );

    fdui->enter = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 180, 60, 30, "Enter^" );
    fl_set_button_shortcut( obj, "^M", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_NORMAL_STYLE + FL_SHADOW_STYLE );
    fl_set_object_callback( obj, cb_stack, 1 );

    fdui->d4 = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 310, 40, 30, "4" );
    fl_set_button_shortcut( obj, "4", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 4 );

    fdui->d5 = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 310, 40, 30, "5" );
    fl_set_button_shortcut( obj, "5", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 5 );

    fdui->d6 = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 310, 40, 30, "6" );
    fl_set_button_shortcut( obj, "6", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 6 );

    fdui->d7 = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 280, 40, 30, "7" );
    fl_set_button_shortcut( obj, "7", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 7 );

    fdui->d8 = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 280, 40, 30, "8" );
    fl_set_button_shortcut( obj, "8", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 8 );

    fdui->d9 = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 280, 40, 30, "9" );
    fl_set_button_shortcut( obj, "9", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 9 );

    fdui->reg_X = obj = fl_add_text( FL_NORMAL_TEXT, 90, 70, 480, 20, "text" );
    fl_set_object_color( obj, FL_BLACK, FL_MCOL );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );

    obj = fl_add_box( FL_UP_BOX, 90, 140, 190, 20, "" );
    fl_set_object_color( obj, FL_WHITE, FL_COL1 );

    fdui->g_radix = fl_bgn_group( );

    fdui->pb_dec = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 190, 90, 50, 20, "DEC" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 2 );
    fl_set_button( obj, 1 );

    fdui->pb_hex = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 90, 90, 50, 20, "HEX" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 1 );

    fdui->pb_bin = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 140, 90, 50, 20, "BIN" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 3 );

    fl_end_group( );

    fdui->g_wsize = fl_bgn_group( );

    fdui->pb_32 = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 140, 140, 50, 20, "32" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 5 );
    fl_set_button( obj, 1 );

    fdui->pb_64 = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 90, 140, 50, 20, "64" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 4 );

    fdui->pb_8 = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 240, 140, 50, 20, "8" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 7 );

    fdui->pb_16 = obj = fl_add_checkbutton( FL_RADIO_BUTTON, 190, 140, 50, 20, "16" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 6 );

    fl_end_group( );

    fdui->lab_signed = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 190, 110, 80, 20, "SIGNED" );
    fl_set_object_color( obj, FL_WHITE, FL_DARKMAGENTA );
    fl_set_object_callback( obj, cb_mode, 0 );

    fdui->d_A = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 250, 40, 30, "A" );
    fl_set_button_shortcut( obj, "Aa", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 10 );

    fdui->d_B = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 250, 40, 30, "B" );
    fl_set_button_shortcut( obj, "Bb", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 11 );

    fdui->d_C = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 250, 40, 30, "C" );
    fl_set_button_shortcut( obj, "Cc", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 12 );

    fdui->d_D = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 220, 40, 30, "D" );
    fl_set_button_shortcut( obj, "Dd", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 13 );

    fdui->d_E = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 220, 40, 30, "E" );
    fl_set_button_shortcut( obj, "Ee", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 14 );

    fdui->d_F = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 220, 40, 30, "F" );
    fl_set_button_shortcut( obj, "Ff", 1 );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_digit, 15 );

    fdui->b_clx = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 180, 40, 30, "CLx" );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 0 );

    fdui->b_drop = obj = fl_add_button( FL_NORMAL_BUTTON, 140, 180, 40, 30, "R\\/" );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_stack, 0 );

    fdui->reg_Z = obj = fl_add_text( FL_NORMAL_TEXT, 90, 30, 480, 20, "text" );
    fl_set_object_color( obj, FL_BOTTOM_BCOL, FL_MCOL );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );

    fdui->reg_T = obj = fl_add_text( FL_NORMAL_TEXT, 90, 10, 480, 20, "text" );
    fl_set_object_color( obj, FL_BOTTOM_BCOL, FL_MCOL );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 70, 20, 20, "X:" );
    fl_set_object_color( obj, FL_BLUE, FL_MCOL );
    fl_set_object_lcolor( obj, FL_YELLOW );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 50, 20, 20, "Y:" );
    fl_set_object_color( obj, FL_BLUE, FL_MCOL );
    fl_set_object_lcolor( obj, FL_YELLOW );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 30, 20, 20, "Z:" );
    fl_set_object_color( obj, FL_BLUE, FL_MCOL );
    fl_set_object_lcolor( obj, FL_YELLOW );

    obj = fl_add_text( FL_NORMAL_TEXT, 60, 10, 20, 20, "T:" );
    fl_set_object_color( obj, FL_BLUE, FL_MCOL );
    fl_set_object_lcolor( obj, FL_YELLOW );

    obj = fl_add_box( FL_UP_BOX, 20, 90, 60, 20, "Radix:" );
    fl_set_object_color( obj, FL_BLUE, FL_BLUE );
    fl_set_object_lcolor( obj, FL_YELLOW );

    obj = fl_add_box( FL_UP_BOX, 20, 140, 60, 20, "W.Size:" );
    fl_set_object_color( obj, FL_BLUE, FL_BLUE );
    fl_set_object_lcolor( obj, FL_YELLOW );

    fdui->b_swap = obj = fl_add_button( FL_NORMAL_BUTTON, 180, 180, 40, 30, "X/Y" );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_stack, 2 );

    fdui->b_chs = obj = fl_add_button( FL_NORMAL_BUTTON, 260, 180, 40, 30, "CHS" );
    fl_set_object_color( obj, FL_BLACK, FL_COL1 );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_callback( obj, cb_arith, 5 );

    fl_end_form( );

    fdui->calc_top->fdui = fdui;

    return fdui;
}
